TPGP/TPGP/Models/Jobs/Contract.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TPGP.Models.Jobs
{
    public class Contract
    {
        public long Id { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "The Name field is required.")]
        public string Name { get; set; }

        [Display(Name = "Begin Date")]
        [Required(ErrorMessage = "The Begin Date field is required.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MMM/dd}")]
        public DateTime InitDate { get; set; }

        [Display(Name = "End Date")]
        [Required(ErrorMessage = "The End Date field is required.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MMM/dd}")]
        public DateTime EndDate { get; set; }

        [Display(Name = "Bonus")]
        [Required(ErrorMessage = "The Bonus field is required.")]
        public double Bonus { get; set; }

        [Display(Name = "Company")]
        [Required(ErrorMessage = "The Company field is required.")]
        public string Company { get; set; }

        [Display(Name = "Zones")]
        public virtual ICollection<GeographicalZone> Zones { get; set; }

        [Required(ErrorMessage = "The Sector field is required.")]
        public long PortfolioId { get; set; }
        public virtual Portfolio Portfolio { get; set; }

        public Contract()
        {
        }
    }
}

TPGP/TPGP/Models/ViewModels/ContractViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using TPGP.Models.Jobs;

namespace TPGP.Models.ViewModels
{
    public class ContractViewModel
    {
        public Contract Contract { get; set; }
        public string Portfolio { get; set; }

        public IEnumerable<SelectListItem> Portfolios { get; set; }

        public IEnumerable<GeographicalZone> Zones { get; set; }
        public IEnumerable<long> ZonesIds { get; set; }

        public ContractViewModel()
        {            
        }
    }
}

TPGP/TPGP/Models/ViewModels/ContractsViewModel.cs
using PagedList;
using System.Collections.Generic;
using TPGP.Models.Jobs;

namespace TPGP.Models.ViewModels
{
    public class ContractsViewModel
    {
        public IPagedList<Contract> Contracts { get; set; }
        public Portfolio Portfolio { get; set; }

        public IEnumerable<Portfolio> Portfolios { get; set; }
       
        public bool IsListEmpty;

        public ContractsViewModel()
        {
        }
    }
}

TPGP/TPGP/Controllers/ContractController.cs
using PagedList;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TPGP.ActionFilters;
using TPGP.DAL.Interfaces;
using TPGP.Models.Jobs;
using TPGP.Models.ViewModels;

namespace TPGP.Controllers
{
    [CustomAuthorize]
    public class ContractController : Controller
    {
        private readonly IContractRepository contractRepository;
        private readonly IPortfolioRepository portfolioRepository;
        private readonly IGeographicalZoneRepository zoneRepository;
        private readonly IScopeRepository scopeRepository;

        public ContractController(IContractRepository contractRepository,
                                  IPortfolioRepository portfolioRepository,
                                  IGeographicalZoneRepository zoneRepository,
                                  IScopeRepository scopeRepository)
        {
            this.contractRepository = contractRepository;
            this.portfolioRepository = portfolioRepository;
            this.zoneRepository = zoneRepository;
            this.scopeRepository = scopeRepository;
        }

        public ActionResult Index(int? page, string sortOrder, string searchString)
        {
            int noPage = (page ?? 1) - 1;

            var cvm = new ContractsViewModel
            {
                Portfolios = portfolioRepository.GetPortfoliosByUserScope((long)Session["id"])
            };

            if (searchString != null)
                page = 1;

            var contracts = contractRepository.Pagination(c => c.Name, noPage, 10, out int total);
            contracts = zoneRepository.GetAll().Include("Contracts").Where(z => z.Label.ToLower().Contains(searchString.ToLower())).SelectMany(z => z.Contracts);

            if (contracts.Count() == 0)
            {
                cvm.IsListEmpty = true;
                return View(cvm);
            }

            if (!string.IsNullOrEmpty(searchString))
            {
                contracts = contractRepository.GetByFilter(c => c.Name.ToLower().Contains(searchString.ToLower()));
            }

            cvm.Contracts = new StaticPagedList<Contract>(contracts, noPage + 1, Utils.Constants.ITEMS_PER_PAGE, total);

            return View(cvm);
        }

        public ActionResult Details(long id)
        {
            var cvm = new ContractViewModel
            {
                Contract = contractRepository.GetById(id)
            };

            return View(cvm);
        }

        public ActionResult Create()
        {
            var initialPortfolios = portfolioRepository.GetPortfoliosByUserScope((long)Session["id"]);

            initialPortfolios.ToList().ForEach(p => p.Scope = scopeRepository.GetScopeByPortfolio(p.Id) ? "Initial" : "Extent");
            initialPortfolios = initialPortfolios.Where(p => p.Scope == "Initial");

            var cvm = new ContractViewModel
            {
                Portfolios = new SelectList(initialPortfolios, dataValueField: "Id", dataTextField: "Sector"),
                Zones = zoneRepository.GetAll()
            };

            return View(cvm);
        }

        [HttpPost]
        public ActionResult Create(ContractViewModel cvm)
        {
            if (ModelState.IsValid)
            {
                var selectedZones = new List<GeographicalZone>();
                if (cvm.ZonesIds != null)
                {
                    var zonesFromDbs = zoneRepository.GetByFilter(z => cvm.ZonesIds.Contains(z.Id));
                    zonesFromDbs.ToList().ForEach(z => selectedZones.Add(z));
                }

                var userZone = (string)Session["zone"];
                selectedZones.Add(zoneRepository.GetByFilter(z => z.Label == userZone).FirstOrDefault());

                var contract = new Contract
                {
                    Name = cvm.Contract.Name,
                    InitDate = cvm.Contract.InitDate,
                    EndDate = cvm.Contract.EndDate,
                    Bonus = cvm.Contract.Bonus,
                    Company = cvm.Contract.Company,
                    PortfolioId = cvm.Contract.PortfolioId,
                    Zones = selectedZones
                };

                contractRepository.Insert(contract);
                contractRepository.SaveChanges();

                return RedirectToAction("Index", "Portfolio/" + contract.PortfolioId);
            }

            return View();
        }

        public ActionResult Edit(long id)
        {
            var contract = contractRepository.GetById(id);

            var zonesIds = new List<long>();
            contract.Zones.ToList().ForEach(z => zonesIds.Add(z.Id));

            var cvm = new ContractViewModel
            {
                Portfolios = new SelectList(portfolioRepository.GetAll(), dataValueField: "Id", dataTextField: "Sector"),
                Contract = contract,
                Zones = zoneRepository.GetAll(),
                ZonesIds = zonesIds
            };

            return View(cvm);
        }

        [HttpPost]
        public ActionResult Edit(ContractViewModel cvm)
        {
            if (ModelState.IsValid)
            {
                var contract = contractRepository.GetAll().Include("Zones").Where(c => c.Id == cvm.Contract.Id).FirstOrDefault();
                var newZones = zoneRepository.GetAll().Where(z => cvm.ZonesIds.Any(id => id == z.Id));

                contract.Zones.Clear();

                newZones.ToList().ForEach(z => contract.Zones.Add(z));

                contract.Name = cvm.Contract.Name;
                contract.InitDate = cvm.Contract.InitDate;
                contract.EndDate = cvm.Contract.EndDate;
                contract.Bonus = cvm.Contract.Bonus;
                contract.Company = cvm.Contract.Company;
                contract.PortfolioId = cvm.Contract.PortfolioId;

                contractRepository.SaveChanges();

                return RedirectToAction("Index", "Portfolio/" + contract.PortfolioId);
            }

            return View();
        }
    }
}

TPGP/TPGP/Controllers/PortfolioController.cs
using PagedList;
using System.Linq;
using System.Web.Mvc;
using TPGP.ActionFilters;
using TPGP.DAL.Interfaces;
using TPGP.Models.Jobs;
using TPGP.Models.ViewModels;
using TPGP.Utils;

namespace TPGP.Controllers
{
    [CustomAuthorize]
    public class PortfolioController : Controller
    {
        private readonly IContractRepository contractRepository;
        private readonly IPortfolioRepository portfolioRepository;
        private readonly IScopeRepository scopeRepository;
        private readonly IGeographicalZoneRepository zoneRepository;

        public PortfolioController(IContractRepository contractRepository, IPortfolioRepository portfolioRepository,
                                                                           IScopeRepository scopeRepository,
                                                                           IGeographicalZoneRepository zoneRepository)
        {
            this.contractRepository = contractRepository;
            this.portfolioRepository = portfolioRepository;
            this.scopeRepository = scopeRepository;
            this.zoneRepository = zoneRepository;
        }

        public ActionResult Index(int? page, string sortOrder, string searchString)
        {
            int noPage = (page ?? 1) - 1;
            int total = 0;

            if (searchString != null)
                page = 1;

            var portfolios = portfolioRepository.GetPortfoliosByUserScope((long)Session["id"]);
            portfolios.ToList().ForEach(p => p.Scope = scopeRepository.GetScopeByPortfolio(p.Id) ? "Initial" : "Extent");

            if (portfolios.Count() == 0)
                portfolios = portfolioRepository.Pagination(p => p.Sector, noPage, Constants.ITEMS_PER_PAGE, out total);

            if (!string.IsNullOrEmpty(searchString))
                portfolios = portfolios.Where(c => c.Sector.ToLower().Contains(searchString.ToLower()));

            var portfoliosViewModels = new PortfoliosViewModel
            {
                Portfolios = new StaticPagedList<Portfolio>(portfolios, noPage + 1, Constants.ITEMS_PER_PAGE, total)
            };

            return View(portfoliosViewModels);
        }

        public ActionResult Contracts(long id, int? page, string sortOrder, string searchString)
        {
            int noPage = (page ?? 1) - 1;
            var contractsViewModels = new ContractsViewModel
            {
                Portfolio = portfolioRepository.GetById(id)
            };

            if (searchString != null)
                page = 1;

            var contracts = contractRepository.Pagination(p => p.PortfolioId == id, c => c.Name, noPage, Constants.ITEMS_PER_PAGE, out int total);
            contractsViewModels.Portfolio.Scope = scopeRepository.GetScopeByPortfolio(id) ? "Initial" : "Extent";

            string zoneUser = (string)Session["zone"];
            contracts = zoneRepository.GetAll().Include("Contracts").Where(z => z.Label == zoneUser).SelectMany(z => z.Contracts).Where(c => c.PortfolioId == id);

            if (contracts.Count() == 0)
            {
                contractsViewModels.IsListEmpty = true;
                return View(contractsViewModels);
            }

            if (!string.IsNullOrEmpty(searchString))
                contracts = contracts.Where(c => c.Name.ToLower().Contains(searchString.ToLower()));

            contractsViewModels.Contracts = new StaticPagedList<Contract>(contracts, noPage + 1, Constants.ITEMS_PER_PAGE, total);

            return View(contractsViewModels);
        }
    }
}

TPGP/TPGP/Views/Contract/Create.cshtml
@model TPGP.Models.ViewModels.ContractViewModel

@{
    ViewBag.Title = "View";
}

<h1>Creating contract</h1>

@using (Html.BeginForm("Create", "Contract", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Contract.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contract.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.InitDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Contract.InitDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contract.InitDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Contract.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contract.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.Bonus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Contract.Bonus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contract.Bonus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Contract.Company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contract.Company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.Portfolio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.DropDownListFor(model => model.Contract.PortfolioId, Model.Portfolios, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.Zones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="dropdown col-md-2">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Geographical Zones
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <ul class="areas">

                        @foreach (var item in Model.Zones)
                        {
                            <li>
                                <label class="control-label" for="ZonesIds[@item.Id]">@item.Label</label>
                                <input type="checkbox" name="ZonesIds" id="ZonesIds[@item.Id]" value="@item.Id">
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </div>

        <div class="back">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>

    </div>
}

@section js {
    @Scripts.Render("~/scripts/datepicker.js")
    @Scripts.Render("~/scripts/jquery.validate.min.js")
    @Scripts.Render("~/scripts/jquery.validate.unobtrusive.min.js")
}

TPGP/TPGP/Views/Contract/Details.cshtml
@model TPGP.Models.ViewModels.ContractViewModel

@{
    ViewBag.Title = "Details";
}

<h1>@Model.Contract.Name</h1>
<hr />
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Contract.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contract.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contract.InitDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contract.InitDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contract.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contract.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contract.Bonus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contract.Bonus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contract.Company)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contract.Company)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contract.Zones)
        </dt>

        <dd>

            @if (Model.Contract.Zones.Count == 0)
            {
                <div>None</div>
            }

            @foreach (var item in Model.Contract.Zones)
            {
                if (item.Label == (string)Session["zone"])
                {
                    <div><font color="green">@(item.Parent != null ? item.Label + " (" + item.Parent.Label + ", initial zone)" : item.Label)</font></div>
                }
                else
                {
                    <div>@(item.Parent != null ? item.Label + " (" + item.Parent.Label + ")" : item.Label)</div>
                }
            }
    </dl>
</div>

<div class="back">
    @Html.ActionLink("Edit", "Edit", new { id = Model.Contract.Id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Back", "Contracts", "Portfolio", new { id = Model.Contract.PortfolioId }, new { @class = "btn btn-secondary" })
</div>

TPGP/TPGP/Views/Contract/Edit.cshtml
@model TPGP.Models.ViewModels.ContractViewModel

@using (Html.BeginForm("Edit", "Contract", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h1>Editing @Model.Contract.Name</h1>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Contract.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Contract.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contract.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.InitDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Contract.InitDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contract.InitDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Contract.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contract.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.Bonus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Contract.Bonus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contract.Bonus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.Company, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.Contract.Company, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contract.Company, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contract.Portfolio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.DropDownListFor(model => model.Contract.PortfolioId, Model.Portfolios, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contract.Zones, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="dropdown col-md-2">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Geographical Zones
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <ul class="areas">

                    @foreach (var item in Model.Zones)
                    {

                        <li>
                            <label class="control-label" for="ZonesIds[@item.Id]">@item.Label</label>
                            @if (Model.ZonesIds.Any(id => id == item.Id))
                            {
                                <input type="checkbox" name="ZonesIds" id="ZonesIds[@item.Id]" value="@item.Id" checked>
                            }
                            else
                            {
                                <input type="checkbox" name="ZonesIds" id="ZonesIds[@item.Id]" value="@item.Id">
                            }

                        </li>
                    }

                </ul>
            </div>
        </div>
    </div>

    <div class="back">
        <input type="submit" value="Save" class="btn btn-primary" />
        @Html.ActionLink("Back", "Contracts", "Portfolio", new { id = Model.Contract.PortfolioId }, new { @class = "btn btn-secondary" })
    </div>
}

@section js {
    @Scripts.Render("~/scripts/jquery.validate.min.js")
    @Scripts.Render("~/scripts/jquery.validate.unobtrusive.min.js")
    @Scripts.Render("~/scripts/datepicker.js")
    @Scripts.Render("~/scripts/moment.min.js")
}

TPGP/TPGP/Views/Contract/Index.cshtml
@using PagedList.Mvc

@model TPGP.Models.ViewModels.ContractsViewModel

@{
    ViewBag.Title = "Contracts";
}

@section css {
    <link href="@Url.Content("~/Content/PagedList.css")" rel="stylesheet" />
}

<h1>Contracts</h1>
<hr />
@if (!Model.IsListEmpty)
{
    <div class="tools">

        <div class="col-lg-4">
            @Html.ActionLink("Create new contract", "Create", "Contract", null, new { @class = "btn btn-primary" })
        </div>

        <div class="col-lg-4" style="padding-bottom:25px;">

            @using (Html.BeginForm("Index", "Contract", FormMethod.Get))
            {
                <div class="input-group">
                    @Html.TextBox("SearchString", null, new { @class = "form-control", @placeholder = "Search..." })
                    <span class="input-group-btn">
                        <button class="btn btn-secondary" type="submit" value="Search">Search</button>
                    </span>
                </div>
            }

        </div>
    </div>

    <div>
        <table class="table table-striped table-hover">
            <thead class="thead-inverse">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Contracts[0].Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Contracts[0].InitDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Contracts[0].EndDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Contracts[0].Company)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model.Contracts)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.InitDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EndDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Company)
                        </td>
                        <td>
                            @Html.ActionLink("Details", "Details", "Contract", new { id = item.Id }, new { @class = "btn btn-info" })
                        </td>
                    </tr>
                }

            </tbody>
        </table>

        <div class="row pagination pager">
            @Html.PagedListPager(Model.Contracts, page => Url.Action("Index", new { page }))
        </div>
    </div>
}

else
{
    <div class="col-lg-4">
        @Html.ActionLink("Create new contract", "Create", "Contract", null, new { @class = "btn btn-primary" })
    </div>

    <div class="container" style="padding:20px;">
        <div class="alert alert-info">
            <strong>Info!</strong> There is no contract in your geographical zone.
        </div>
    </div>
}